---
apiVersion: v1
kind: Service
metadata:
  name: api-{{ .Values.name }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    app: api-{{ .Values.name }}
